### ISSUE TITLE
NPM Install Error v1.3.2

### ISSUE THREAD

**Issue by Karankang007** [Qix-/node-error-ex#14] opened 2020-02-12 18:12 UTC
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz
npm ERR! 404
npm ERR! 404  'error-ex@1.3.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

```

**Comment by talal7860** [comment] 2020-02-12 18:40
@Karankang007  Looks like a cloud flare caching issue, I used a vpn to connect US, and it worked.

**Comment by mattgrande** [comment] 2020-02-12 20:01
See issue #13

**Comment by Qix-** [comment] 2020-02-12 20:38
Please search before opening issues.

Duplicate of #13. This was an issue with npm.

**Closed** 2020-02-12 20:38 UTC
